[[apps]]
title = 'Kodi'
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/kodi/assets/icon.png"

[apps.runner]
type = 'docker'
name = 'WolfKodi'
image = 'ghcr.io/games-on-whales/kodi:edge'
env = ['RUN_SWAY=true', 'GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*']
devices = []
mounts = []
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "Privileged": false,
    "CapAdd": ["NET_RAW", "MKNOD", "NET_ADMIN"],
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
\
"""